package com.example.myfin.ui.components

enum class SettingsActiveSheet {
    NONE,
    PERSONAL_INFO,
    PROFILE,
    VAULT_STRATEGY,
    VAULT_ACCOUNTS,
    AUTO_SWEEP_THRESHOLD,
    FORTRESS_SAFETY_NET,
    BIOMETRIC_CONFIRM,
    CHANGE_PIN,
    DAILY_REMINDER,
    REMINDERS,
    COUNTRY_CURRENCY_PICKER,
    RESET_CONFIRM,
    STRATEGY,
    SECURITY,
    NOTIFICATIONS,
    CURRENCY,
    BACKUP,
    DATA_MANAGEMENT
}
